### ISSUE TITLE
monitor elasticsearch with zabbix

### ISSUE THREAD

**Issue by baiju1** [icy/zabbix-es#1]
Dear Sir,
 post on github (https://github.com/serialsito/Elasticsearch-zabbix) regarding elasticsearch-zabbix, i tried a lot to get successfully monitor ES but failed, i thing m doing something wrong : i want to know where we have to put .py and .userparm file , is this will be configure over zabbix server or over ES-client which i want to monitor ? 

by configuring .py and .userparm over zabbix-server i got this error : 
item [test:ESzabbix[cluster,status]] became not supported: ZBX_NOTSUPPORTED
  1299:20150409:110848.606 item [test:ESzabbix[cluster,unassigned_shards]] became not supported: ZBX_NOTSUPPORTED
  1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},field_size_in_bytes]] became not supported: ZBX_NOTSUPPORTED
  1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},filter_size_in_bytes]] became not supported: ZBX_NOTSUPPORTED
  1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},index_total]] became not supported: ZBX_NOTSUPPORTED
  1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},size_in_bytes]] became not supported: ZBX_NOTSUPPORTED
  1299:20150409:110848.608 item [test:ESzabbix[service,status]] became not supported: ZBX_NOTSUPPORTED

**Comment by icy** [comment]
Hi @baiju1 . My tool has nothing related to https://github.com/serialsito/Elasticsearch-zabbix regarding internal code. My tool use `Perl`, not `Python`. 

I suggest you to open a support request here https://github.com/serialsito/Elasticsearch-zabbix/issues .

Thank you.

**Comment by baiju1** [comment]
sorry its my first post so by mistake i post under ur tool, by the way i have read ur tool also and while importing the template in zabbix-server it says Unknown import version...
Actually sir i just want to monitor elasticsearch with zabbix no matter whose tool m using..
